### ISSUE TITLE
Required Internet access (?)

### ISSUE THREAD

**Issue by gstavrinos** [rubedos/viper_ros#2]
Hey guys,

We've been playing around with viper, and although everything plays just fine in our laptop, when we connect the camera to the internal switch of our robot (in which there is no internet access), the camera's web interface does not load completely, and there is no way to run the required ROS nodes. This happens with our laptop too, if we disconnect it from the internet.

Is Internet access really required for viper to work? This is a huge problem for us, since we want to use it for outdoor navigation. 

Any advice would be greatly appreciated. Thanks in advance,

George

**Comment by ArnasRS** [comment]
Hello George,

Have you managed to solve the issue? Have you contacted our support?

I can verify that internet access is not required for the camera.

Arnas

**Comment by gstavrinos** [comment]
Hey Arnas,

Yes, the issue is now solved. The internal switch of our robot was not forwarding all packets to the robot's computer.

Internet access is indeed not required.

Thanks,

George
